### ISSUE TITLE
Streams order changed between terraform plan and apply

### ISSUE THREAD

**Issue by Jrmyy** [airbytehq/terraform-provider-airbyte#83] opened 2024-02-20 14:08 UTC
👋🏻 Hello

I am seing a strange behaviour in the terraform provider. A connection which is not updated will appear in the state (`terraform plan`) as modified because the streams list order can change over time.

This is problematic because we discard fields we don't want to synchronize to our destination but when terraform applies the change on the connection, it will reset the fields selection, which is far from ideal.

Is there a way to ensure consistency of streams order ?

**Comment by Lau-ie** [comment] 2024-05-02 06:34
I'm also getting this weird behaviour.

Terrafrom plan lists that a lot of connections will be updated in-place where only the order of the streams changes. When I try to apply anyway I run into [Issue 91](https://github.com/airbytehq/terraform-provider-airbyte/issues/91) where it errors out because it thinks there is a primary key configured.

**Comment by hongbo-miao** [comment] 2024-07-02 01:42
Another similar ticket https://github.com/airbytehq/terraform-provider-airbyte/issues/70
Hopefully @szemek 's [pull request](https://github.com/airbytehq/terraform-provider-airbyte/pull/111) to fix this can be merged soon ☺️

**Closed** 2024-07-29 07:02 UTC

**Comment by hongbo-miao** [comment] 2024-10-22 03:20
Tested on the Airbyte provider version 0.6.5. Confirmed the issue has been fixed, thanks! ☺️
