### ISSUE TITLE
Provider produced inconsistent result after apply when using pre-defined primary keys

### ISSUE THREAD

**Issue by DDynamic** [airbytehq/terraform-provider-airbyte#66] opened 2023-12-06 20:00 UTC
The MySQL source defines primary keys, so we should not pass them when using `sync_mode = incremental_deduped_history`.

```
resource "airbyte_connection" "mysql_to_bigquery" {
  configurations = {
    streams = [
      {
        name = "my_table"
        sync_mode = "incremental_deduped_history"
      }
    ]
  }
 ...
}
```

However, after applying, `primary_key` gets set in state:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to airbyte_connection.mysql_to_bigquery, provider "provider[\"registry.terraform.io/airbytehq/airbyte\"]" produced an unexpected new value: .configurations.streams[0].primary_key: was
│ null, but now cty.ListVal([]cty.Value{cty.ListVal([]cty.Value{cty.StringVal("id")})}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Then, subsequent modifications to the resource fail because the update API request includes the `primary_key`:

```
│ {"type":"https://reference.airbyte.com/reference/errors","title":"bad-request","status":400,"detail":"The body of the request contains an invalid connection configuration. Primary key for stream: my_table is
│ already pre-defined. Please do NOT include a primary key configuration for this stream."}
```

**Comment by Santhin** [comment] 2023-12-12 08:14
I am encountering the same error after updating an existing connection via Terraform. As a workaround, I have to remove the connection and recreate it with new changes.

**Comment by ThomasRooney** [comment] 2024-02-05 19:03
Closing as a duplicate of #70; very much agree this isn't great behaviour and should get fixed.

**Closed by ThomasRooney** 2024-02-05 19:03 UTC
